// <auto-generated />
using System;
using HygieTestAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HygieTestAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251016143615_ajout-stock-1")]
    partial class ajoutstock1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HygieTestAPI.Models.Entities.Bieres", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrasseriesId")
                        .HasColumnType("uuid");

                    b.Property<int>("Degre")
                        .HasColumnType("integer");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Prix")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BrasseriesId");

                    b.ToTable("bieres");
                });

            modelBuilder.Entity("HygieTestAPI.Models.Entities.Brasseries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("brasseries");
                });

            modelBuilder.Entity("HygieTestAPI.Models.Entities.Grossistes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("grossistes");
                });

            modelBuilder.Entity("HygieTestAPI.Models.Entities.Stocks", b =>
                {
                    b.Property<Guid>("BieresId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrossistesId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("BieresId", "GrossistesId");

                    b.HasIndex("GrossistesId");

                    b.ToTable("stocks");
                });

            modelBuilder.Entity("HygieTestAPI.Models.Entities.Bieres", b =>
                {
                    b.HasOne("HygieTestAPI.Models.Entities.Brasseries", "Brasserie")
                        .WithMany()
                        .HasForeignKey("BrasseriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brasserie");
                });

            modelBuilder.Entity("HygieTestAPI.Models.Entities.Stocks", b =>
                {
                    b.HasOne("HygieTestAPI.Models.Entities.Bieres", "Biere")
                        .WithMany()
                        .HasForeignKey("BieresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HygieTestAPI.Models.Entities.Grossistes", "Grossiste")
                        .WithMany()
                        .HasForeignKey("GrossistesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biere");

                    b.Navigation("Grossiste");
                });
#pragma warning restore 612, 618
        }
    }
}
